#!/usr/bin/env python3

from argparse import ArgumentParser

DESCRIPTION = "A python script for scraping website using CSS selectors"
parser = ArgumentParser(description = DESCRIPTION)

parser.add_argument("selector", help="CSS selector to query")
parser.add_argument("file", nargs="?", default=None,
                    help="file to scrape. Default reading from standard input")

parser.add_argument("--delim", help="delimeter between printed outputs", action="store")
parser.add_argument("-a", "--attr", help="attributes to print", action="append", dest="attr")
parser.add_argument("-s", "--string", action="append_const", dest="attr", const=0,
                    help="print the string within tag") 
parser.add_argument("-e", "--element", action="append_const", dest="attr", const=1,
                    help="print whole element. Default if attr or string is not specified")

def main():
    args = parser.parse_args()
    print(args)

if __name__ == '__main__':
    main()
